---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: notify
  type: slack-notification
  source:
    url: ((slack-webhook))
- name: new-version
  type: git
  source:
    uri: https://github.com/95rade/concourse-tutorial.git
    branch: develop

jobs:
- name: test-slack
  public: true
  serial: true
  plan:
  - get: new-version
    trigger: true
  - task: test-sometimes-works
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: new-version
      outputs:
      - name: notify_message
      run:
        path: new-version/tutorials/miscellaneous/slack-notifications/test-sometimes-works-notify-message.sh
    on_success:
      put: notify
      params:
        text_file: notify_message/message
        silent: true
    on_failure:
      put: notify
      params:
        text_file: notify_message/message
        silent: true